baseurl: "//ycpcs.github.io/cs456-spring2020"
markdown: kramdown
highlighter: rouge
coursename: "CS 456"

kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
